fail build when invalid builder is selected

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -62,6 +62,14 @@ jobs:
         ports:
           - 3306:3306    # Opens tcp port 3306 on the host and service container
     steps:
+      # Fail job when invalid builder is selected
+      - name: Check BUILDER environment variable
+        if: ${{! contains(fromJSON('["docker", "maven"]'), env.BUILDER) }}
+        run: |
+          echo "Invalid builder: ${{ env.BUILDER }}"
+          echo 'Builders: ["docker", "maven"]'
+          exit 1
+
       - name: Clone
         uses: actions/checkout@v4    # https://github.com/marketplace/actions/checkout
 
